version: "3.8"
services:
  app:
    container_name: app-container
    hostname: app-server
    build: ./docker/python
    volumes:
      - ./src:/workspace
    ports:
      - 8000:8000
    restart: always
    tty: true
